### ISSUE TITLE
does not work for me on nixOs

### ISSUE THREAD

**Issue by Lotbert** [f-fusco/gummy#31]
Hi,

foremost, thanks a lot for this tool!

I installed gummy through home-manager on nixOS and can't make it work, typing `gummy start` and then `gummy -b 5`. Nothing changes after executing the commands, of course I have also tested other vals for `-b` between `0` and `100`. I don't see any error message.

What follows is some output that maybe helps:  

output of `ls /sys/bus/iio/devices/`  
```shell
iio:device0  trigger0
```

output of `ls /sys/bus/iio/devices/iio:device0`  
```shell
buffer                     in_illuminance_hysteresis_relative  in_intensity_both_raw             in_intensity_scale  trigger
buffer0                    in_illuminance_offset               in_intensity_hysteresis           name                uevent
current_timestamp_clock    in_illuminance_raw                  in_intensity_hysteresis_relative  power
dev                        in_illuminance_sampling_frequency   in_intensity_offset               scan_elements
in_illuminance_hysteresis  in_illuminance_scale                in_intensity_sampling_frequency   subsystem
```

output of `cat ~/.config/gummyconf`  
``` shell
{
    "als_polling_rate": 5000,
    "brt_auto_fps": 60,
    "screens": [
        {
            "brt_auto_max": 500,
            "brt_auto_min": 125,
            "brt_auto_offset": 0,
            "brt_auto_polling_rate": 1000,
            "brt_auto_speed": 1000,
            "brt_auto_threshold": 8,
            "brt_mode": 0,
            "brt_step": 500,
            "temp_auto": false,
            "temp_step": 500
        }
    ],
    "temp_auto": false,
    "temp_auto_fps": 45,
    "temp_auto_high": 6500,
    "temp_auto_low": 3400,
    "temp_auto_speed": 60,
    "temp_auto_sunrise": "06:00",
    "temp_auto_sunset": "16:00"
}
```

**Comment by Fushko** [comment]
Hello,

unfortunately the NixOS package is very outdated. I have contacted the package mantainer months ago, but never got a response back.

You should be running v0.3. The program was almost completely rewritten from that release, I'm afraid I can't be of much help here.

**Comment by Lotbert** [comment]
Yes i am on v0.3 . Thanks for the fast response anyway.

**Comment by Lotbert** [comment]
Hi, just to let you know a colleague just issued an update request here:  
https://github.com/NixOS/nixpkgs/issues/259004
