### ISSUE TITLE
Query current brightness / temperature

### ISSUE THREAD

**Issue by jorismertz** [f-fusco/gummy#33]
Hey, would it be possible to add a command to query the current brightness and temperature values? This would make scripting with gummy a lot more convenient, e.g. creating a polybar module to show and control these values.

I've already tried to implement this myself, but I'm too inexperienced with C++ to make sense of the codebase. Maybe if anyone could give me some pointers on where to start, I could at least try to make a working prototype.

Thanks :)

**Comment by Fushko** [comment]
Hi, yes, it would be possible. I'm not familiar with polybar though. How should the CLI format screen data?

**Comment by jorismertz** [comment]
Polybar allows you to create your own modules by passing it a shell script.
I think it would be fine to just print it in a format where you can use something like awk to extract the desired value.

**Comment by Fushko** [comment]
Example output of `gummy status` in 0.5.6:

```
[screen 0] backlight: 48% (ALS), brightness: 100%, temperature: 6500K (time)
[screen 1] backlight: 20%, brightness: 100%, temperature: 6500K (time)
```

Values set on automatic modes will show their mode in parentheses. In the above example, the backlight of the first screen is handled by the ambient light sensor, while temperature of both screens is handled by the specified time range.

This is just the first iteration, let me know if this is ideal for your case.
