### ISSUE TITLE
Consider Git submodules instead Fetchcontent?

### ISSUE THREAD

**Issue by redtide** [f-fusco/gummy#35]
AFAIK some (many?) Linux distributions don't permit network connection when packaging, nor downloading during build.
I think it would be good to replace Fetchcontent with git submodules and some CMake options to disable bundled dependencies to let packagers use the system installed ones.
I use Archlinux and I see that all dependencies exists as system packages.

**Comment by f-fusco** [comment]
> AFAIK some (many?) Linux distributions don't permit network connection when packaging, nor downloading during build.

Can you name one?

> I think it would be good to replace Fetchcontent with git submodules

Makes no sense. I don't work on the code of the libraries I'm using.

> CMake options to disable bundled dependencies to let packagers use the system installed ones.

I could do that.

**Comment by redtide** [comment]
"Can you name one?" "Makes no sense" are not really answer for someone having in mind to contribute a gui tool, so never mind.

**Comment by f-fusco** [comment]
One would expect a GUI developer to ask me about a proper API.

**Comment by redtide** [comment]
Have done already other UI without asking anything at all, this was the only thing that made me loose time with a problem with the AUR -git package that fired errors about fmt files already installed.

**Comment by f-fusco** [comment]
Yeah, a cmake option to use external libraries is a good solution to your concern, as I agreed to. Changing the package manager is wild, though.

**Comment by redtide** [comment]
Which package manager?

**Comment by redtide** [comment]
Tried today and it works.

> One would expect a GUI developer to ask me about a proper API.

It would be nice to have some documentation, meanwhile I just use QProcess to run commands via command line as described in the README.

I was wondering why not using DBUS instead BTW.

As side note: while looking the `gummyd` logic, I noticed that Arch guidelines [discourage](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette) the use of `/usr/libexec/`; could you add a flag to disable that installation, e.g.
```cmake
if(NOT DEFINED GUMMY_CUSTOM_DAEMON_PATH)
    set(CMAKE_INSTALL_DAEMON_PATH "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBEXECDIR}/gummyd")
    message("-- Daemon path: " ${CMAKE_INSTALL_DAEMON_PATH})
    target_compile_definitions(libgummyd PRIVATE CMAKE_INSTALL_DAEMON_PATH="${CMAKE_INSTALL_DAEMON_PATH}")
    target_compile_features(libgummyd PRIVATE cxx_std_20)
else()
    message("-- Daemon path: ${GUMMY_CUSTOM_DAEMON_PATH}")
endif()
```
so for Arch would be set to `/usr/share/gummy/` in the package script instead?

**Comment by redtide** [comment]
Anyways, I did [this](https://github.com/qtilities/gummy-conf) simple/stupid configuration tool (including [AUR](https://aur.archlinux.org/packages/gummy-conf-git) package). Has some little issue and not much attractive as it was yours in Gammy, but works for me.

**Comment by f-fusco** [comment]
> I was wondering why not using DBUS instead BTW.

Yes, maybe someday.

> As side note: while looking the gummyd logic, I noticed that Arch guidelines [discourage](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette) the use of /usr/libexec/; could you please add a flag to disable that installation (or me via PR if you want)

I wouldn't worry too much about it. (gummy's AUR package maintainer never complained about it). But feel free to make a PR and I'll merge.

> Anyways, I did [this](https://github.com/qtilities/gummy-conf) simple/stupid configuration tool (including [AUR](https://aur.archlinux.org/packages/gummy-conf-git) package). Has some little issue and not much attractive as it was yours in Gammy, but works for me.

Cool! I'll check it out.

**Comment by redtide** [comment]
> I wouldn't worry too much about it. (gummy's AUR package maintainer never complained about it).

From the AUR home page:
> AUR packages are user produced content. Any use of the provided files is at your own risk

so he might be not even aware about some package rules; I just found it and I also have my own packages (I didn't even know there was a libexec directory!).

> But feel free to make a PR and I'll merge.

Cool, I'll do it.

**Comment by f-fusco** [comment]
> I didn't even know there was a libexec directory!

According to this [spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html#idm236091914528) and [and this one](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html), libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. 

That was the rationale for putting gummyd in there. But I guess lib/ or whatever can be used the same nowadays.
